# Form implementation generated from reading ui file 'e:\VS Code\Python\Rebral Login\outros\tela_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 750)
        MainWindow.setStyleSheet("background-color: rgb(138, 211, 246);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: rgba(0, 128, 0, 0)\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(320, 303, 250, 27))
        self.lineEdit_login.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setStyleSheet("background: rgba(0, 128, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 304, 24, 24))
        self.label_5.setMinimumSize(QtCore.QSize(24, 24))
        self.label_5.setMaximumSize(QtCore.QSize(24, 24))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("e:\\VS Code\\Python\\Rebral Login\\outros\\login.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(320, 360, 250, 27))
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_senha.setFont(font)
        self.lineEdit_senha.setStyleSheet("background: rgba(0, 128, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 360, 24, 24))
        self.label_3.setMinimumSize(QtCore.QSize(24, 24))
        self.label_3.setMaximumSize(QtCore.QSize(24, 24))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("e:\\VS Code\\Python\\Rebral Login\\outros\\senha.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(340, 440, 200, 40))
        self.pushButton_login.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_login.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(600, 450, 150, 30))
        self.pushButton_voltar.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_voltar.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 701, 601))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 90, 661, 541))
        self.label_4.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 140, 240, 100))
        self.label_6.setMinimumSize(QtCore.QSize(240, 100))
        self.label_6.setMaximumSize(QtCore.QSize(240, 100))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("e:\\VS Code\\Python\\Rebral Login\\outros\\logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_2.raise_()
        self.label_4.raise_()
        self.lineEdit_login.raise_()
        self.label_5.raise_()
        self.lineEdit_senha.raise_()
        self.label_3.raise_()
        self.pushButton_login.raise_()
        self.pushButton_voltar.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "  Login"))
        self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "  Senha"))
        self.pushButton_login.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
